steps:
  - name: 'python'
    args: ["make", "ci"]
    env:
      - 'BUCKET_NAME=$_BUCKET_NAME'
      - 'JOB_DIR=$_JOB_DIR'
      - 'TRAINING_PACKAGE_PATH=$_TRAINING_PACKAGE_PATH'
      - 'MAIN_TRAINER_MODULE=$_MAIN_TRAINER_MODULE'
      - 'REGION=$_REGION'
      - 'RUNTIME_VERSION=$_RUNTIME_VERSION'
      - 'PYTHON_VERSION=$_PYTHON_VERSION'
      - 'SCALE_TIER=$_SCALE_TIER'