dir_name = "gs://cloud-samples-data/ml-engine/iris"
iris_data_filename = "iris_data.csv"
iris_target_filename = "iris_target.csv"
model_filename = "model.pkl"
model_upload_format = "iris_%Y%m%d_%H%M%S"
